### ISSUE TITLE
По поводу replace и replaceIn в minecraft{}

### ISSUE THREAD

**Issue by BlackSauronEx** [Hummel009/MC-Environments#1]
Раньше, в обычном градле для 1.7.10 можно было использовать нечто подобное:
minecraft {
    replace("@TEST@", "Work")
    replaceIn("test.java")
}
Этот код означал, что при компиляции в файле test.java значение @TEST@ изменится на Work.

А есть ли что-то подобное для retro futura gradle для 1.7.10?
Я перепробовал кучу способов и пока не могу добиться нужного результата
Таких функций как replace и replaceIn в minecraft {} просто нет
И да, извиняюсь если неправильно вопрос задал, но вроде эту ситуацию можно и как проблему обозначить, я не очень хорошо ориентируюсь на Гите

**Comment by BlackSauronEx** [comment]
Вроде решил эту проблему добавлением следующего кода:
```
repositories {
    maven {
        name = "GTNH Maven"
        url = uri("https://nexus.gtnewhorizons.com/repository/public/")
    }
}

minecraft {
    val tags = mapOf(
            "@MOD_ID@" to modId,
            "@MOD_NAME@" to modName,
            "@MOD_VERSION@" to modVersion,
            "@MOD_DEPENDS@" to modDepends
    )
    injectedTags.putAll(tags)
    tagReplacementFiles.add("Reference.java")
}
```

**Comment by Hummel009** [comment]
О, вижу, я немного опоздал. В любом случае, я не знал ответ на этот вопрос, так как сам не пользовался этой фичей. Но это может пригодиться, буду знать, спасибо!
